sdm845-common: Build dummy android.hidl.[base,manager]@1.0
 * Required by Oreo-MR0 blobs

 * But actually this..

error: device/xiaomi/sdm845-common/powerstats/Android.bp:15:1: module "android.hardware.power.stats@1.0-service.xiaomi" variant "android_vendor.31_arm64_armv8-2a_kryo385": depends on //system/libhidl:libhidltransport which is not visible to this module

Signed-off-by: XtremeOrnob <xtreme.ornob@gmail.com>